live_config_reload = true

import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 12

[env]
TERM = "xterm-256color"
