live_config_reload = true

import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
